# See with https://github.com/google/mono_repo.dart for details on this file
dart:
- 2.14.0
- dev

stages:
- smoke_test:
  - group:
    - format
    - analyze: --fatal-infos .
    dart: [dev]
  - group:
    - analyze:
    dart: [2.14.0]
- unit_test:
  - group:
    - test
